Add 'date_part' function to PostgresModule
zio/zio-sql pull request #288
Opened 2020-11-21 15:45 UTC by riccardocorbella

Fixes #206

2020-11-22 20:46 UTC, robmwalsh requested changes
Thanks for your work on this! I think this should work with proper rendering of literals but unfortunately this will need to wait for issue #311 to be resolved (which will break your literal trick, as this will be escaped to an SQL string)

2020-11-22 20:46 UTC, robmwalsh commented on core/jvm/src/main/scala/zio/sql/expr.scala
> +      case TypeTag.TInstant => Expr.literal(s"TIMESTAMP '$a'").asInstanceOf[Expr[Features.Literal, Any, A]]
Can you revert this change please? see comment at https://github.com/zio/zio-sql/pull/307#discussion_r528286267

2020-11-23 23:20 UTC, jczuchnowski commented on core/jvm/src/main/scala/zio/sql/expr.scala
> +    implicit def literal[A](a: A)(implicit typeTag: TypeTag[A]): Expr[Features.Literal, Any, A] = typeTag match {
Let's go back to the initial shorter form ;)

2020-11-25 22:49 UTC, jczuchnowski commented
@riccardocorbella just one small fix and we're good to go!

2020-11-27 20:58 UTC, riccardocorbella commented
@jczuchnowski #311 is still open, I think that I'm blocked unless I use the version of literal that @robmwalsh asked me to revert above...

2020-11-27 21:01 UTC, robmwalsh commented
@riccardocorbella I think that's ready to go now, just need @jczuchnowski to confirm he's happy with it to merge, then we should be able to get this one in

2020-11-28 15:56 UTC, jczuchnowski commented
@riccardocorbella https://github.com/zio/zio-sql/pull/317 has been merged

2023-07-27 12:19 UTC, jczuchnowski approved these changes

2023-07-27 12:20 UTC, merged