rederDelete for SqlServer
zio/zio-sql pull request #477
Opened 2021-07-01 14:23 UTC by eqk

2021-07-01 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-sql?pullRequest=477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-sql?pullRequest=477) before we can accept your contribution.<br/><hr/>**Крылов Данил** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-sql?pullRequest=477) it.</sub>

2021-07-01 15:14 UTC, jczuchnowski requested changes
Great work! But in addition to that, could you please add a new ReadSpec with two short tests that would check for a proper handling of `.isTrue` and `.isNotTrue` ? It's very specific to SQL Server and I wouldn't want it to fall through the cracks at some point.

2021-07-01 15:14 UTC, jczuchnowski commented on mysql/src/test/scala/zio/sql/TestContainer.scala
> +          mysqlImageVersion = Option(imageName).map(DockerImageName.parse).map(_.asCompatibleSubstituteFor("mysql"))
This shouldn't be part of this PR.

2021-07-08 07:48 UTC, eqk commented
> Great work! But in addition to that, could you please add a new ReadSpec with two short tests that would check for a proper handling of `.isTrue` and `.isNotTrue` ? It's very specific to SQL Server and I wouldn't want it to fall through the cracks at some point.

I have some problems with ReadSpec, because of default where clause in select builder [here](https://github.com/zio/zio-sql/blob/master/core/jvm/src/main/scala/zio/sql/select.scala#L13) . With initial query like this 
`val query =
  select(Count(customerId))
    .from(customers)
    .where(verified.isTrue)`

It renders to this 
`select count(customers.id) from customers where true and customers.verified = 1`
Witch is not valid. What is the purpose of this clause? Maybe redefine SelectBuilder in this module? @jczuchnowski

2021-07-08 10:17 UTC, eqk commented
#480 need to redefine `where true` interpretation in SQLServer module

2021-07-08 10:21 UTC, robmwalsh commented
How about changing to an Option for the where expression in Read.Select?

2022-02-14 19:48 UTC, sviezypan commented
hi @eqk problems with sql server and booleans were resolved in #529 , if you would resolve conflicts on this PR, we could merge it

2022-02-27 10:20 UTC, sviezypan approved these changes

2022-02-27 19:39 UTC, jczuchnowski approved these changes

2022-02-27 19:40 UTC, merged