Add makedate function to MysqlSqlModule #655
zio/zio-sql pull request #671
Opened 2022-05-26 12:11 UTC by peixunzhang

2022-05-26 12:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-sql?pullRequest=671) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-sql?pullRequest=671) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-sql?pullRequest=671) it.</sub>

2022-05-26 13:51 UTC, sviezypan requested changes
Just one comment and its good to go.
Also please format. I might have broken formatting when I was resolving conflicts from github directly.

2022-05-26 13:51 UTC, sviezypan commented on mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala
>        assertion.mapErrorCause(cause => Cause.stackless(cause.untraced))
Lets simplify with 
`assertZIO(testResult.runHead.some)(equalTo(expected))`

2022-05-26 14:38 UTC, jczuchnowski commented on mysql/src/main/scala/zio/sql/mysql/MysqlSqlModule.scala
> +import java.time.LocalDate
Duplicated import. LocalDate is imported couple of lines above.

2022-05-27 09:04 UTC, sviezypan approved these changes

2022-05-27 09:46 UTC, merged