added soundex function - closes zio#660
zio/zio-sql pull request #684
Opened 2022-05-26 15:27 UTC by lukemcphee

2022-05-26 18:51 UTC, sviezypan requested changes
hi @lukemcphee I added some minor comments. Can you also please check why tests and formatting are failing?

2022-05-26 18:51 UTC, sviezypan commented on mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala
> +      assertion.mapErrorCause(cause => Cause.stackless(cause.untraced))
let's change to
assertZIO(testResult.runHead.some)(equalTo(expected))

2022-05-26 18:51 UTC, sviezypan commented on mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala
> +      assertion.mapErrorCause(cause => Cause.stackless(cause.untraced))
Lets simplify
```
val assertion = for {
        robertResult <- resultForRobert.runCollect
        rupertResult <- resultForRupert.runCollect
      } yield assert(robertResult.head.equals(rupertResult.head))(equalTo(true))

      assertion.mapErrorCause(cause => Cause.stackless(cause.untraced))
```

to just
```
for {
        robertResult <- resultForRobert.runCollect
        rupertResult <- resultForRupert.runCollect
      } yield assert(robertResult.head.equals(rupertResult.head))(equalTo(true))
```

2022-05-26 18:51 UTC, sviezypan commented on mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala
> +      assertion.mapErrorCause(cause => Cause.stackless(cause.untraced))
same as below

2022-05-30 20:21 UTC, jczuchnowski approved these changes

2022-05-30 20:23 UTC, merged