Make null primitive value return None
zio/zio-sql pull request #876
Opened 2023-06-08 13:44 UTC by tonykwok1992

Currently selecting rows with null value in a nullable int/long columns will gives Some(0) even when the schema object field has type Option[Int], due to the fact that resultSet.getInt(columnIndex) gives 0 for null value rather than null,

2023-06-08 13:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-sql?pullRequest=876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-sql?pullRequest=876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-sql?pullRequest=876) it.</sub>

2023-06-08 13:45 UTC, tonykwok1992 commented on postgres/src/test/scala/zio/sql/postgresql/SelectSpec.scala
> +        rating = None
This is Some(0) before the change

2023-06-11 17:44 UTC, tonykwok1992 commented
Hello, can I get a review on this? thanks!

2023-06-12 07:52 UTC, sviezypan requested changes
hi @tonykwok1992 thank you for this work, this is great catch and fix. Just 2 minor comments and then its good to be merged.

2023-06-12 07:52 UTC, sviezypan commented on postgres/src/test/scala/zio/sql/postgresql/SelectSpec.scala
> +object SelectSpec extends PostgresRunnableSpec with DbSchema {
would you move this to PostgresSqlModuleSpec? as there are also tests for selects

2023-06-12 07:52 UTC, sviezypan commented on postgres/src/test/scala/zio/sql/postgresql/SelectSpec.scala
> +      insertAssertion.mapErrorCause(cause => Cause.stackless(cause.untraced))
I think it would work if you just return the for comprehension directly?

2023-06-12 09:16 UTC, merged